language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libmaxminddb-dev libjansson-dev

script: cmake . && make
